# Generated by Django 4.2.1 on 2023-05-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academicos', '0002_docente_especialidad_curso_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='especialidad',
        ),
    ]
